-- Execute conectado ao database desafio_bancario_correcao.
-- A ordem evita erros de chave estrangeira.

CREATE TABLE IF NOT EXISTS public.tipos_conta (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(40) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS public.pessoas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(120) NOT NULL,
    cpf VARCHAR(11) NOT NULL UNIQUE,
    email VARCHAR(160) NOT NULL,
    CONSTRAINT ck_pessoas_cpf CHECK (cpf ~ '^[0-9]{11}$')
);

CREATE TABLE IF NOT EXISTS public.contas_bancarias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agencia VARCHAR(4) NOT NULL,
    numero VARCHAR(8) NOT NULL,
    saldo NUMERIC(15, 2) NOT NULL DEFAULT 0,
    ativa BOOLEAN NOT NULL DEFAULT TRUE,
    titular_id BIGINT NOT NULL,
    tipo_conta_id BIGINT NOT NULL,
    CONSTRAINT uk_contas_agencia_numero UNIQUE (agencia, numero),
    CONSTRAINT ck_contas_agencia CHECK (agencia ~ '^[0-9]{4}$'),
    CONSTRAINT ck_contas_numero CHECK (numero ~ '^[0-9]{6}-[0-9]$'),
    CONSTRAINT ck_contas_saldo CHECK (saldo >= 0),
    CONSTRAINT fk_contas_titular
        FOREIGN KEY (titular_id)
        REFERENCES public.pessoas (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    CONSTRAINT fk_contas_tipo
        FOREIGN KEY (tipo_conta_id)
        REFERENCES public.tipos_conta (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS idx_contas_titular_id
    ON public.contas_bancarias (titular_id);

CREATE INDEX IF NOT EXISTS idx_contas_tipo_conta_id
    ON public.contas_bancarias (tipo_conta_id);

SELECT table_name
FROM information_schema.tables
WHERE table_schema = 'public'
  AND table_name IN ('tipos_conta', 'pessoas', 'contas_bancarias')
ORDER BY table_name;

